services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app/backend
      - ./training:/app/training

  dashboard:
    build:
      context: ./website
      args:
        - NEXT_PUBLIC_ENV_URL=http://backend:8000
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_ENV_URL=http://backend:8000
    depends_on:
      - backend
